### ISSUE TITLE
playing nice with Fugitive

### ISSUE THREAD

**Issue by AlainPilon** [nyarly/cadre#11]
First of, I really like Cadre. Problem is that I like/need fugitive and since installing Cadre I cant see the changes in my left margin.

Is there anyway to toggle cadre on/off or to display both Fugitive and Cadre  in the left margin at the same time?

**Comment by nyarly** [comment]
The default plugin has two commands defined: :Cov and :Uncov which will enable and disable the coverage signs, respectively. The vim "signs" functionality doesn't have support for overlapping signs, unfortunately, so I'm afraid the two tools won't really work well together.

There's also a Vim plugin called vim-legend which is essentially the cadre plugin file extracted into a proper project, which (among other things) has a Toggle command, so you don't even have to write that.

All in all, I might set up mappings to Uncov | EnableFugitive and DisableFugitive | Cov if I were you.

**Comment by AlainPilon** [comment]
@nyarly that is exactly what I am going to do. Thanks!
